language: python
# python versions to use during the tests
python:
    - "2.7"
    - "3.4"
# command to install dependencies
install:
    - pip install -r test_requirements.txt
    - pip install .
# command to run tests
script:
    - py.test --cov-report term-missing --cov=./distances
#    - py.test
branches:
  only:
   - master
after_success:
    - coveralls