language: python
# python versions to use during the tests
python:
    - "3.6"
# command to install dependencies
install:
    - pip install -r test_requirements.txt
    - pip install .
# command to run tests
script:
    - pytest --cov-report term-missing --cov=distances
after_success:
    - coveralls